#!/usr/bin/env node
/**
 * Generates the Alight-style project XML for "The ATM That Printed Tomorrow's Money".
 * Source of truth: story/scenes.json  →  Output: project/atm-tomorrow-money.xml
 *
 * Run: bun tools/gen-project.js
 */
import fs from "fs";
import path from "path";

const __dirname = import.meta.dirname;

const scenes = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "story", "scenes.json"), "utf8"));

const MOOD_GRADE = {
  shock: "#ef4444", empathy: "#fbbf24", mystery: "#f59e0b", wonder: "#22d3ee",
  panic: "#dc2626", revelation: "#22d3ee", twist: "#a78bfa", climax: "#f97316", warm: "#fde68a",
};
const MOTION = ["zoom-in", "zoom-out", "pan-left", "pan-right", "zoom-in", "pan-left"];

const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

const xml = [];
xml.push(`<?xml version="1.0" encoding="UTF-8"?>`);
xml.push(`<!-- ============================================================ -->`);
xml.push(`<!--  ${scenes.title} (${scenes.titleHi})                          -->`);
xml.push(`<!--  Alight-style project XML · generated by tools/gen-project.js -->`);
xml.push(`<!--  Render with: bun workflow/render.js --project project/atm-tomorrow-money.xml -->`);
xml.push(`<!-- ============================================================ -->`);
xml.push(`<project`);
xml.push(`  title="${esc(scenes.title)}"`);
xml.push(`  subtitle="${esc(scenes.titleHi)}"`);
xml.push(`  channel="${esc(scenes.channel)}"`);
xml.push(`  width="1920" height="1080" fps="${scenes.fps}" duration="${scenes.duration}"`);
xml.push(`  audioDir="voiceover"`);
xml.push(`>`);
xml.push(``);
xml.push(`  <info>`);
xml.push(`    Tagline: ${esc(scenes.tagline)}`);
xml.push(`    Genre: Time-travel suspense / moral twist · Style: Chroma Toons 2D flat cartoon`);
xml.push(`    Audio: record narration (Hinglish) → voiceover/vo-full.mp3  (optional, auto-muxed)`);
xml.push(`  </info>`);
xml.push(``);
xml.push(`  <assets>`);
const bgSet = new Set();
for (const s of scenes.scenes) bgSet.add(s.bg);
for (const bg of [...bgSet]) {
  xml.push(`    <asset id="${esc(bg.replace(/\.svg$/, ""))}" src="public/assets/${esc(bg)}" />`);
}
xml.push(`  </assets>`);
xml.push(``);
xml.push(`  <audio>`);
xml.push(`    <track src="voiceover/vo-full.mp3" label="Full narration (Hinglish)" offset="0" loop="false" />`);
xml.push(`  </audio>`);
xml.push(``);
xml.push(`  <captions font="workflow/fonts/DejaVuSans-Bold.ttf" size="64" color="#fde68a"`);
xml.push(`    boxColor="rgba(0,0,0,0.55)" position="0.84" lineSpacing="1.15" maxLines="2" />`);
xml.push(``);
xml.push(`  <scenes>`);
for (const s of scenes.scenes) {
  const grade = MOOD_GRADE[s.mood] || "#fbbf24";
  xml.push(`    <scene id="${esc(s.id)}" start="${s.start}" end="${s.end}"`);
  xml.push(`      bg="${esc(s.bg.replace(/\.svg$/, ""))}" motion="${MOTION[s.start % MOTION.length]}"`);
  xml.push(`      grade="${grade}" vignette="0.5" transition="fade" title="${esc(s.title)}">`);
  xml.push(`      <caption>${esc(s.vo)}</caption>`);
  xml.push(`    </scene>`);
}
xml.push(`  </scenes>`);
xml.push(`</project>`);

const outPath = path.join(__dirname, "..", "project", "atm-tomorrow-money.xml");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, xml.join("\n") + "\n");
console.log(`✔ Wrote ${outPath} (${scenes.scenes.length} scenes, ${scenes.duration}s @ ${scenes.fps}fps)`);
